# This workflow creates an npm package and deploys it to npmjs

name: Deploy to npmjs

on: workflow_dispatch

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Node
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt-get install -y curl
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Build and Deploy to npmjs
        run: |
          npm ci
          npm run build
          npm run build:expo-plugin
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}">.npmrc
          npm publish